image: 'rust:latest'

stages:
  - check
  - test

check:
  stage: check
  script:
    - rustc --version
    - cargo --version
    - cargo check --verbose

test:
  stage: test
  script:
    - rustc --version
    - cargo --version
    - cargo test --verbose
