[package]
name = "ccl"
version = "1.1.0"
authors = ["acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://gitlab.nebulanet.cc/xacrimon/ccl"
homepage = "https://gitlab.nebulanet.cc/xacrimon/ccl"
description = "blazing fast concurrect datastructures for Rust"
documentation = "https://docs.rs/ccl"

[dependencies]
fxhash = "0.2.1"
hashbrown = "0.2.1"
parking_lot = "0.7.1"
smallvec = "0.6.9"
rand = "0.6.5"
