[package]
name = "ccl"
version = "0.2.2"
authors = ["acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://gitlab.com/xacrimon/ccl"
homepage = "https://gitlab.com/xacrimon/ccl"
description = "blazing fast concurrent collections for rust"
documentation = "https://docs.rs/ccl/0.2.1/ccl"

[dependencies]
swym = "0.1.0-preview"
fxhash = "0.2.1"
hashbrown = { version = "0.1.8", features = ["nightly"] }
seahash = "3.0.6"
parking_lot = { version = "0.7.1", features = ["nightly"] }
smallvec = "0.6.9"
