[package]
name = "ccl"
version = "1.2.3"
authors = ["acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://gitlab.nebulanet.cc/xacrimon/ccl"
homepage = "https://gitlab.nebulanet.cc/xacrimon/ccl"
description = "blazing fast concurrect datastructures for Rust"
documentation = "https://docs.rs/ccl"

[features]
default = ["std"]
std = ["rand", "ccl-fxhash/std", "parking_lot"]
no_std = ["spin", "hashbrown/nightly"]

[dependencies]
ccl-fxhash = { version = "3.0.0", default-features = false }
spin = { version = "0.5", optional = true }
hashbrown = { version = "0.2.1" }
parking_lot = { version = "0.7.1", optional = true }
smallvec = { version = "0.6.9", default-features = false }
rand = { version = "0.6.5", optional = true }
