[package]
name = "ccl"
version = "0.5.3"
authors = ["acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://gitlab.nebulanet.cc/xacrimon/ccl"
homepage = "https://gitlab.nebulanet.cc/xacrimon/ccl"
description = "blazing fast datastructures for Rust"
documentation = "https://docs.rs/ccl"

[dependencies]
fxhash = "0.2.1"
hashbrown = { version = "0.2.0", features = ["nightly"] }
parking_lot = { version = "0.7.1", features = ["nightly"] }
smallvec = "0.6.9"
rand = "0.6.5"
