[package]
name = "ccl"
version = "0.2.3"
authors = ["acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://gitlab.com/xacrimon/ccl"
homepage = "https://gitlab.com/xacrimon/ccl"
description = "blazing fast concurrent collections for rust"
documentation = "https://docs.rs/ccl"

[dependencies]
fxhash = "0.2.1"
hashbrown = { version = "0.1.8", features = ["nightly"] }
parking_lot = { version = "0.7.1", features = ["nightly"] }
smallvec = "0.6.9"
