[package]
name = "ccl-bench"
version = "0.1.0"
authors = ["Acrimon <joel.wejdenstal@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.2"
rayon = "1.0"
lazy_static = "1.3.0"
ccl = { path = ".." }
jemallocator = "0.3.0"

[[bench]]
name = "dhashmap"
harness = false
